name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # try to build
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    # run all tests
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  linting:

    runs-on: ubuntu-latest
    steps:
    # Install Rust nightly toolchain
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
        override: true
    
    # cargo fmt
    - uses: actions/checkout@v3
    - name: fmt
      run: cargo +nightly fmt --all --check

    # run cargo clippy
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo +nightly clippy --all

  cross-testing:
    strategy:
      matrix:
        rust: [stable, nightly, 1.41]
        os: [ubuntu-latest, windows-latest, macos-latest]
        feature: [default, with-serde]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cross compile
        run: cargo test --verbose --features ${{ matrix.feature }}
